import React, { createContext, useContext, useState, ReactNode } from 'react';
export type Language = 'es' | 'en' | 'zh';
interface LanguageContextType { language: Language; setLanguage: (lang: Language) => void; t: (key: string) => string;}

const translations: Record<Language, Record<string, string>> = {
  es: {
    'nav.about': 'Sobre Nosotros',
    'nav.featured': 'Platos',
    'nav.locations': 'Sedes',
    'nav.reviews': 'Reseñas',
    'nav.socials': 'Redes',
    'nav.orderNow': 'Pedir Ahora',
    'nav.home': 'Inicio',
    'nav.menu': 'Menú',
    'hero.tagline': '¡LA MEJOR COMIDA DIRECTA A TU MESA!',
    'hero.cta': 'Hacer Pedido',
    'about.title': 'Sobre Nosotros',
    'about.default': 'En Panda Express, nos apasiona brindar la mejor experiencia gastronómica. Frescura, calidad y el sabor que nos caracteriza en cada pedido.',
    'featured.badge': 'Favoritos del Panda',
    'featured.title': 'Platos Destacados',
    'featured.viewAll': 'Ver todo el menú',
    'locations.badge': 'Encuéntranos',
    'locations.title': 'Nuestras Sedes',
    'locations.open': 'Abierto Ahora',
    'locations.closed': 'Cerrado',
    'reviews.badge': 'Comunidad Panda',
    'reviews.title': 'Lo que dicen nuestros clientes',
    'socials.title': '¡Únete a la familia!',
    'socials.tagline': 'Síguenos en nuestras redes para no perderte ninguna promoción bomba y sorteos exclusivos.',
    'cta.title': '¿Con hambre?',
    'cta.button': 'Ver Menú Completo',
    'menu.welcome': '¡Buen provecho!',
    'menu.empty': 'No hay productos aquí',
    'menu.ready': 'Listo para pedir',
    'menu.viewCart': 'Ver Carrito',
    'menu.total': 'Total',
    'menu.price': 'Precio',
    'menu.outOfStock': 'Agotado',
    'cart.title': 'Tu Pedido',
    'cart.checkout': 'Finalizar Pago',
    'cart.empty': 'Tu carrito está vacío',
    'cart.emptyTagline': '¡Agrega algo delicioso para comenzar!',
    'cart.specialInstructions': '¿Alguna instrucción especial?',
    'cart.delivery': 'Delivery',
    'cart.fullName': 'Nombre completo',
    'cart.whatsapp': 'WhatsApp de contacto',
    'cart.address': 'Dirección exacta de entrega',
    'cart.mapSelect': 'Seleccionar en el mapa',
    'cart.reference': 'Punto de referencia (Color de casa, local cercano...)',
    'cart.mapTitle': 'Ubicación de entrega',
    'cart.mapTagline': 'Arrastra el mapa hasta tu puerta',
    'cart.closeMap': 'Cerrar Mapa',
    'cart.shipping': 'Costo de Envío',
    'cart.orderTotal': 'Total del Pedido',
    'cart.inBolivares': 'En Bolívares',
    'cart.continue': 'Continuar al Pago',
    'cart.back': 'Volver',
    'cart.confirmWhatsApp': 'Enviar pedido al WhatsApp',
    'cart.mapHint': 'Toca el mapa para fijar tu ubicación',
    'cart.useLocation': 'Usar mi ubicación actual',
    'cart.locating': 'Localizando...',
    'cart.error.nameMin': 'Nombre debe tener al menos 2 caracteres',
    'cart.error.phoneInvalid': 'Número de teléfono inválido',
    'cart.error.addressMin': 'Dirección muy corta',
    'cart.error.addressOutOfRange': 'Dirección fuera del área de cobertura',
    'cart.error.unknown': 'Error desconocido',
    'cart.outOfCoverage': 'Fuera de cobertura',
    'cart.closed': 'Cerrado',
    'welcome.greeting': '¡Bienvenido!',
    'welcome.selectLocation': 'Selecciona tu sede favorita',
    'welcome.noLocations': 'No hay sedes disponibles en este momento',
    'welcome.admin': 'Configuración del Sistema',
    'cat.combos': 'Combos',
    'cat.especiales': 'Especiales',
    'cat.raciones': 'Raciones',
    'cat.entradas': 'Entradas',
    'cat.bebidas': 'Bebidas',
    'loc.prebo.name': 'Prebo',
    'loc.prebo.address': 'Av. Andrés Eloy Blanco, Valencia',
    'loc.naguanagua.name': 'Naguanagua',
    'loc.naguanagua.address': 'CC La Granja, Naguanagua',
    'loc.san-diego.name': 'San Diego',
    'loc.san-diego.address': 'Av. Don Julio Centeno, San Diego',
    'prod.combo1.name': 'Combo #1',
    'prod.combo1.desc': 'Pollo frito Panda (3 piezas) + Papas fritas o Chopsuey especial',
    'prod.combo2.name': 'Combo #2',
    'prod.combo2.desc': 'Pollo frito Panda (6 piezas) + Papas fritas o Chopsuey especial',
    'prod.combo3.name': 'Combo #3',
    'prod.combo3.desc': 'Pollo frito Panda (12 piezas) + Papas fritas o Chopsuey especial',
    'prod.combo4.name': 'Combo #4',
    'prod.combo4.desc': 'Pollo frito Panda (6 piezas) + Chopsuey especial + 2 Lumpia vegetales + 4 Pollo agridulce + Papas fritas',
    'prod.combo5.name': 'Combo #5',
    'prod.combo5.desc': 'Arroz frito especial (camarón, pollo y jamón) + 6 Pollo agridulce + Papas fritas',
    'prod.combo6.name': 'Combo #6',
    'prod.combo6.desc': 'Arroz frito especial (camarón, pollo y jamón) + Chopsuey especial + 6 Costilla sal y pimienta',
    'prod.combo7.name': 'Combo #7',
    'prod.combo7.desc': 'Arroz frito especial (camarón, pollo y jamón) + Chopsuey especial + 1 Lumpia vegetales',
    'prod.combo8.name': 'Combo #8',
    'prod.combo8.desc': 'Arroz frito especial (camarón, pollo y jamón) + Chopsuey especial + 1 Costilla asada',
    'prod.combo9.name': 'Combo #9',
    'prod.combo9.desc': 'Arroz frito especial (camarón, pollo y jamón) + Papas fritas + 1 Costilla asada',
    'prod.combo10.name': 'Combo #10',
    'prod.combo10.desc': 'Arroz frito especial (camarón, pollo y jamón) + 1 Lumpia vegetales + 6 Costilla sal y pimienta',
    'prod.combo11.name': 'Combo #11',
    'prod.combo11.desc': 'Arroz frito especial (camarón, pollo y jamón) + Papas fritas + 6 Costilla sal y pimienta',
    'prod.combo12.name': 'Combo #12',
    'prod.combo12.desc': 'Arroz frito especial (camarón, pollo y jamón) + Pollo agridulce (3 piezas) + 3 Costilla sal y pimienta',
    'prod.combo13.name': 'Combo #13',
    'prod.combo13.desc': 'Arroz frito especial (camarón, pollo y jamón) + Pollo agridulce (6 piezas) + Chopsuey especial',
    'prod.combo14.name': 'Combo #14',
    'prod.combo14.desc': 'Arroz frito especial (camarón, pollo y jamón) + Pollo agridulce (6 piezas) + 1 Lumpia vegetales',
    'prod.combo15.name': 'Combo #15',
    'prod.combo15.desc': 'Arroz frito especial (camarón, pollo y jamón) + 1 Costilla asada + 1 Lumpia vegetales',
    'prod.combo16.name': 'Combo #16',
    'prod.combo16.desc': 'Arroz frito especial (camarón, pollo y jamón) + Papas fritas + Chopsuey especial',
    'prod.combo17.name': 'Combo #17',
    'prod.combo17.desc': 'Arroz frito especial (camarón, pollo y jamón) + Pollo agridulce (3 piezas) + 1 Costilla asada',
    'prod.combo18.name': 'Combo #18',
    'prod.combo18.desc': 'Arroz frito especial (camarón, pollo y jamón) + Papas fritas + 1 Lumpia vegetales',
    'prod.combo19.name': 'Combo #19',
    'prod.combo19.desc': 'Media ración arroz frito especial (camarón, pollo y jamón) + Chopsuey especial',
    'prod.combo20.name': 'Combo #20',
    'prod.combo20.desc': 'Media ración arroz frito especial (camarón, pollo y jamón) + 3 porciones pollo agridulce',
    'prod.combo21.name': 'Combo #21',
    'prod.combo21.desc': 'Media ración arroz frito especial (camarón, pollo y jamón) + 1 pollo frito',
    'prod.combo22.name': 'Combo #22',
    'prod.combo22.desc': 'Arroz frito especial (camarón, pollo y jamón) + 2 pollo frito + Papas fritas o Chopsuey especial',
    'prod.combo23.name': 'Combo #23',
    'prod.combo23.desc': 'Arroz frito + Pollo con piña + Papa o Chopsuey',
    'prod.combo24.name': 'Combo #24',
    'prod.combo24.desc': 'Arroz frito + Pollo ajonjolí + Papa o Chopsuey',
    'prod.esp1.name': 'Arroz frito especial',
    'prod.esp1.desc': 'Arroz frito especial (camarón, pollo y jamón)',
    'prod.esp2.name': 'Media arroz frito especial',
    'prod.esp2.desc': 'Media ración arroz frito especial (camarón, pollo y jamón)',
    'prod.esp3.name': 'Chopsuey especial',
    'prod.esp3.desc': 'Chopsuey especial (camarón, pollo y jamón)',
    'prod.esp4.name': 'Media Chopsuey especial',
    'prod.esp4.desc': 'Media ración Chopsuey especial (camarón, pollo y jamón)',
    'prod.rac1.name': 'Pollo con vegetales',
    'prod.rac1.desc': 'Pollo con vegetales (120 gr)',
    'prod.rac2.name': 'Pollo agridulce',
    'prod.rac2.desc': 'Pollo agridulce (15 und)',
    'prod.rac3.name': 'Pollo miel y ajonjolí',
    'prod.rac3.desc': 'Pollo miel y ajonjolí (15 und)',
    'prod.rac4.name': 'Costillas sal y pimienta',
    'prod.rac4.desc': 'Costillas sal y pimienta (320 gr)',
    'prod.rac5.name': 'Costillas asadas',
    'prod.rac5.desc': 'Costillas asadas (4 und)',
    'prod.rac6.name': 'Camarón sal y pimienta',
    'prod.rac6.desc': 'Camarón sal y pimienta (30/40 und aprox)',
    'prod.rac7.name': 'Tallarines',
    'prod.rac7.desc': 'Tallarines (camarón, pollo y jamón)',
    'prod.rac8.name': 'Media tallarines',
    'prod.rac8.desc': 'Media ración de tallarines (camarón, pollo y jamón)',
    'prod.ent1.name': 'Papas fritas',
    'prod.ent1.desc': 'Ración papas fritas (280 gr)',
    'prod.ent2.name': 'Lumpia de vegetales',
    'prod.ent2.desc': 'Ración lumpia de vegetales (2 und)',
    'prod.beb1.name': 'Agua Minalba 355 ml',
    'prod.beb1.desc': 'Agua Minalba 355 ml',
    'prod.beb2.name': 'Agua Minalba 600 ml',
    'prod.beb2.desc': 'Agua Minalba 600 ml',
    'prod.beb3.name': 'Botella de Malta 250 ml',
    'prod.beb3.desc': 'Botella de Malta 250 ml',
    'prod.beb4.name': 'Lata de Malta 355 ml',
    'prod.beb4.desc': 'Lata de Malta 355 ml',
    'prod.beb5.name': 'Gatorade 500 ml',
    'prod.beb5.desc': 'Gatorade 500 ml',
    'prod.beb6.name': 'Lipton 500 ml',
    'prod.beb6.desc': 'Lipton 500 ml',
    'prod.beb7.name': 'Lata de refresco 355 ml',
    'prod.beb7.desc': 'Lata de refresco 355 ml',
    'prod.beb8.name': 'Refresco 1 lt',
    'prod.beb8.desc': 'Refresco 1 lt',
    'prod.beb9.name': 'Refresco 1.5 lt',
    'prod.beb9.desc': 'Refresco 1.5 lt',
    'prod.beb10.name': 'Refresco 2 lt',
    'prod.beb10.desc': 'Refresco 2 lt',
    'prod.beb11.name': 'Yukery 250 ml',
    'prod.beb11.desc': 'Yukery 250 ml',
    'rev.0.name': 'Juan Pérez',
    'rev.0.body': 'La mejor comida china que he probado. El sabor es auténtico y las porciones son generosas.',
    'rev.1.name': 'Maria Garcia',
    'rev.1.body': 'El servicio es increíblemente rápido. Pedí a domicilio y llegó caliente y fresco en 20 minutos.',
    'rev.2.name': 'Carlos Ruiz',
    'rev.2.body': 'Excelente calidad-precio. Las sedes son muy limpias y el ambiente es genial para comer con amigos.',
    'rev.3.name': 'Ana Lopez',
    'rev.3.body': 'Amo el pollo agridulce, tiene la textura perfecta. Definitivamente mi lugar favorito para los domingos.',
    'legal.pageTitle': 'Aviso Legal',
    'legal.metaDescription': 'Términos y Condiciones y Política de Privacidad de Wallace Panda Express.',
    'legal.backHome': 'Volver al Inicio',
    'legal.title': 'Aviso Legal',
    'legal.lastUpdated': 'Última actualización: junio 2026',
    'legal.nav.terms': 'Términos',
    'legal.nav.privacy': 'Privacidad',
    'legal.terms.title': 'Términos y Condiciones',
    'legal.terms.s1.title': '1. Aceptación de los Términos',
    'legal.terms.s1.text': 'Al acceder y utilizar la plataforma de pedidos en línea de Wallace Panda Express, usted acepta estos Términos y Condiciones en su totalidad. Si no está de acuerdo con alguno de estos términos, le recomendamos no utilizar nuestro servicio.',
    'legal.terms.s2.title': '2. Descripción del Servicio',
    'legal.terms.s2.p1': 'Wallace Panda Express pone a su disposición una plataforma digital que le permite realizar pedidos de comida para delivery o recolección en cualquiera de nuestras sedes ubicadas en Valencia, Naguanagua y San Diego.',
    'legal.terms.s2.p2': 'El proceso de pedido se realiza a través de nuestra aplicación web y se confirma vía WhatsApp. Wallace Panda Express no procesa pagos directamente a través de la plataforma; el pago se acuerda directamente con la sede al momento de la entrega o recolección.',
    'legal.terms.s3.title': '3. Pedidos y Pagos',
    'legal.terms.s3.p1': 'Al realizar un pedido a través de nuestra plataforma, usted declara:',
    'legal.terms.s3.li1': 'Que la información proporcionada (nombre, dirección, teléfono) es veraz y está actualizada.',
    'legal.terms.s3.li2': 'Que los precios están expresados en Dólares (USD). El monto total se calcula al tipo de cambio del BCV (Banco Central de Venezuela) vigente al día del pedido.',
    'legal.terms.s3.li3': 'Que los impuestos aplicables se incluyen en el total mostrado al momento del pedido.',
    'legal.terms.s3.li4': 'Que el costo de delivery, cuando aplique, se indica antes de confirmar el pedido.',
    'legal.terms.s4.title': '4. Delivery y Recolección',
    'legal.terms.s4.p1': 'Los tiempos de entrega son estimados y pueden variar según la ubicación, la demanda y las condiciones climáticas. Wallace Panda Express no garantiza tiempos de entrega exactos.',
    'legal.terms.s4.p2': 'El cliente es responsable de proporcionar una dirección de entrega precisa y accesible. Si el domicilio no se encuentra dentro del área de cobertura de la sede, el pedido no podrá ser procesado para delivery.',
    'legal.terms.s5.title': '5. Cancelaciones y Reembolsos',
    'legal.terms.s5.p1': 'Una vez confirmado el pedido vía WhatsApp, las cancelaciones deben gestionarse directamente comunicándose con la sede correspondiente lo antes posible.',
    'legal.terms.s5.p2': 'No se realizan reembolsos bajo ninguna circunstancia. Una vez confirmado el pedido, el monto pagado no es reembolsable. Es responsabilidad del cliente verificar su pedido antes de confirmarlo.',
    'legal.terms.s6.title': '6. Obligaciones del Usuario',
    'legal.terms.s6.p1': 'Al utilizar nuestro servicio, el usuario se compromete a:',
    'legal.terms.s6.li1': 'Proporcionar información veraz y completa al realizar pedidos.',
    'legal.terms.s6.li2': 'No utilizar la plataforma para fines ilícitos, fraudulentos o que atenten contra el buen funcionamiento del servicio.',
    'legal.terms.s6.li3': 'Tratar con respeto al personal de delivery y de las sedes.',
    'legal.terms.s7.title': '7. Propiedad Intelectual',
    'legal.terms.s7.text': 'Todo el contenido presente en esta plataforma, incluyendo pero no limitado a textos, gráficos, logotipos, imágenes, videos, diseño del menú y software, es propiedad de Wallace Panda Express y está protegido por las leyes de propiedad intelectual vigentes. Queda prohibida su reproducción, distribución o modificación sin autorización expresa.',
    'legal.terms.s8.title': '8. Limitación de Responsabilidad',
    'legal.terms.s8.p1': 'Wallace Panda Express no se hace responsable por reacciones alérgicas o efectos adversos derivados del consumo de nuestros productos. Es responsabilidad del cliente informar sobre cualquier alergia o restricción alimentaria al momento de realizar el pedido.',
    'legal.terms.s8.p2': 'No nos hacemos responsables por interrupciones del servicio debidas a fallas técnicas, mantenimiento del sistema, fuerza mayor o circunstancias fuera de nuestro control razonable.',
    'legal.terms.s9.title': '9. Cambios en los Términos',
    'legal.terms.s9.text': 'Wallace Panda Express se reserva el derecho de modificar estos Términos y Condiciones en cualquier momento. Los cambios entrarán en vigor inmediatamente después de su publicación en esta página. El uso continuado de la plataforma después de los cambios constituye la aceptación de los mismos.',
    'legal.terms.s10.title': '10. Contacto',
    'legal.terms.s10.text': 'Si tiene preguntas o inquietudes sobre estos Términos y Condiciones, puede comunicarse con nosotros a través de nuestros canales oficiales de WhatsApp o visitando cualquiera de nuestras sedes.',
    'legal.privacy.title': 'Política de Privacidad',
    'legal.privacy.s1.title': '1. Información que Recopilamos',
    'legal.privacy.s1.p1': 'Para procesar sus pedidos y mejorar nuestro servicio, recopilamos la siguiente información:',
    'legal.privacy.s1.li1': 'Nombre completo al realizar un pedido.',
    'legal.privacy.s1.li2': 'Número de teléfono de contacto (WhatsApp).',
    'legal.privacy.s1.li3': 'Dirección de entrega y datos de ubicación geográfica cuando utiliza el mapa.',
    'legal.privacy.s1.li4': 'Instrucciones especiales o notas adicionales proporcionadas voluntariamente.',
    'legal.privacy.s2.title': '2. Uso de la Información',
    'legal.privacy.s2.p1': 'Utilizamos su información exclusivamente para:',
    'legal.privacy.s2.li1': 'Procesar y entregar su pedido de manera eficiente.',
    'legal.privacy.s2.li2': 'Comunicarnos con usted respecto a su pedido a través de WhatsApp.',
    'legal.privacy.s2.li3': 'Mejorar la calidad de nuestro servicio y la experiencia del usuario.',
    'legal.privacy.s3.title': '3. Compartir su Información',
    'legal.privacy.s3.p1': 'Su información personal es compartida únicamente con la sede de Wallace Panda Express que procesará su pedido. No vendemos, alquilamos ni compartimos su información con terceros para fines de marketing o publicidad.',
    'legal.privacy.s3.p2': 'Podremos divulgar su información únicamente cuando sea requerido por ley o por orden de autoridades competentes.',
    'legal.privacy.s4.title': '4. Seguridad de los Datos',
    'legal.privacy.s4.text': 'Implementamos medidas de seguridad técnicas y organizativas para proteger su información personal contra acceso no autorizado, alteración, divulgación o destrucción. Sin embargo, ningún método de transmisión por Internet o almacenamiento electrónico es 100% seguro, por lo que no podemos garantizar seguridad absoluta.',
    'legal.privacy.s5.title': '5. Cookies y Tecnología de Rastreo',
    'legal.privacy.s5.text': 'Nuestra plataforma puede utilizar cookies y tecnologías similares para mejorar su experiencia de navegación, recordar sus preferencias y analizar el uso del servicio. Puede configurar su navegador para rechazar cookies, aunque esto podría afectar el funcionamiento de la plataforma.',
    'legal.privacy.s6.title': '6. Sus Derechos',
    'legal.privacy.s6.p1': 'Usted tiene derecho a:',
    'legal.privacy.s6.li1': 'Solicitar acceso a la información personal que tenemos sobre usted.',
    'legal.privacy.s6.li2': 'Solicitar la corrección de datos inexactos o desactualizados.',
    'legal.privacy.s6.li3': 'Solicitar la eliminación de su información personal de nuestros registros.',
    'legal.privacy.s7.title': '7. Menores de Edad',
    'legal.privacy.s7.text': 'Nuestro servicio no está dirigido a menores de 18 años. No recopilamos intencionalmente información personal de menores de edad. Si usted es padre o tutor y sabe que su hijo nos ha proporcionado información personal, contáctenos para que podamos eliminarla.',
    'legal.privacy.s8.title': '8. Cambios en esta Política',
    'legal.privacy.s8.text': 'Wallace Panda Express se reserva el derecho de actualizar esta Política de Privacidad en cualquier momento. Los cambios serán publicados en esta página con la fecha de la última actualización. Le recomendamos revisar esta política periódicamente.',
    'legal.privacy.s9.title': '9. Contacto',
    'legal.privacy.s9.text': 'Para consultas sobre esta Política de Privacidad o sobre el tratamiento de sus datos personales, puede comunicarse con nosotros a través de nuestros canales oficiales de WhatsApp o visitando cualquiera de nuestras sedes.',
  },
  en: {
    'nav.about': 'About Us',
    'nav.featured': 'Dishes',
    'nav.locations': 'Locations',
    'nav.reviews': 'Reviews',
    'nav.socials': 'Socials',
    'nav.orderNow': 'Order Now',
    'nav.home': 'Home',
    'nav.menu': 'Menu',
    'hero.tagline': 'THE BEST FOOD STRAIGHT TO YOUR TABLE!',
    'hero.cta': 'Place Order',
    'about.title': 'About Us',
    'about.default': 'At Panda Express, we are passionate about providing the best dining experience. Freshness, quality, and our characteristic flavor in every order.',
    'featured.badge': 'Panda Favorites',
    'featured.title': 'Featured Dishes',
    'featured.viewAll': 'View full menu',
    'locations.badge': 'Find Us',
    'locations.title': 'Our Locations',
    'locations.open': 'Open Now',
    'locations.closed': 'Closed',
    'locations.closedToday': 'Currently Closed',
    'reviews.badge': 'Panda Community',
    'reviews.title': 'What our customers say',
    'socials.title': 'Join the family!',
    'socials.tagline': 'Follow us on our networks to not miss any bomb promotions and exclusive giveaways.',
    'cta.title': 'Hungry?',
    'cta.button': 'View Full Menu',
    'menu.welcome': 'Enjoy your meal!',
    'menu.empty': 'No products here',
    'menu.ready': 'Ready to order',
    'menu.viewCart': 'View Cart',
    'menu.total': 'Total',
    'menu.price': 'Price',
    'menu.outOfStock': 'Out of Stock',
    'cart.title': 'Your Order',
    'cart.checkout': 'Checkout',
    'cart.empty': 'Your cart is empty',
    'cart.emptyTagline': 'Add something delicious to start!',
    'cart.specialInstructions': 'Any special instructions?',
    'cart.delivery': 'Delivery',
    'cart.fullName': 'Full name',
    'cart.whatsapp': 'Contact WhatsApp',
    'cart.address': 'Exact delivery address',
    'cart.mapSelect': 'Select on map',
    'cart.reference': 'Reference point (House color, nearby store...)',
    'cart.mapTitle': 'Delivery Location',
    'cart.mapTagline': 'Drag the map to your door',
    'cart.closeMap': 'Close Map',
    'cart.shipping': 'Shipping Fee',
    'cart.orderTotal': 'Order Total',
    'cart.inBolivares': 'In Bolivares',
    'cart.continue': 'Continue to Payment',
    'cart.back': 'Back',
    'cart.confirmWhatsApp': 'Order via WhatsApp',
    'cart.mapHint': 'Tap the map to set your location',
    'cart.useLocation': 'Use my current location',
    'cart.locating': 'Locating...',
    'cart.error.nameMin': 'Name must be at least 2 characters',
    'cart.error.phoneInvalid': 'Invalid phone number',
    'cart.error.addressMin': 'Address too short',
    'cart.error.addressOutOfRange': 'Address out of delivery area',
    'cart.error.unknown': 'Unknown error',
    'cart.outOfCoverage': 'Out of coverage',
    'cart.closed': 'Closed',
    'welcome.greeting': 'Welcome!',
    'welcome.selectLocation': 'Select your favorite location',
    'welcome.noLocations': 'No locations available right now',
    'welcome.admin': 'System Configuration',
    'cat.combos': 'Combos',
    'cat.especiales': 'Special',
    'cat.raciones': 'Portions',
    'cat.entradas': 'Appetizers',
    'cat.bebidas': 'Drinks',
    'loc.prebo.name': 'Prebo',
    'loc.prebo.address': 'Andres Eloy Blanco Ave, Valencia',
    'loc.naguanagua.name': 'Naguanagua',
    'loc.naguanagua.address': 'La Granja Mall, Naguanagua',
    'loc.san-diego.name': 'San Diego',
    'loc.san-diego.address': 'Don Julio Centeno Ave, San Diego',
    'prod.combo1.name': 'Combo #1',
    'prod.combo1.desc': 'Panda fried chicken (3 pcs) + French fries or Special chopsuey',
    'prod.combo2.name': 'Combo #2',
    'prod.combo2.desc': 'Panda fried chicken (6 pcs) + French fries or Special chopsuey',
    'prod.combo3.name': 'Combo #3',
    'prod.combo3.desc': 'Panda fried chicken (12 pcs) + French fries or Special chopsuey',
    'prod.combo4.name': 'Combo #4',
    'prod.combo4.desc': 'Panda fried chicken (6 pcs) + Special chopsuey + 2 Veggie lumpia + 4 Sweet sour chicken + Fries',
    'prod.combo5.name': 'Combo #5',
    'prod.combo5.desc': 'Special fried rice (shrimp, chicken, ham) + 6 Sweet sour chicken + Fries',
    'prod.combo6.name': 'Combo #6',
    'prod.combo6.desc': 'Special fried rice (shrimp, chicken, ham) + Special chopsuey + 6 Salt pepper ribs',
    'prod.combo7.name': 'Combo #7',
    'prod.combo7.desc': 'Special fried rice (shrimp, chicken, ham) + Special chopsuey + 1 Veggie lumpia',
    'prod.combo8.name': 'Combo #8',
    'prod.combo8.desc': 'Special fried rice (shrimp, chicken, ham) + Special chopsuey + 1 Grilled rib',
    'prod.combo9.name': 'Combo #9',
    'prod.combo9.desc': 'Special fried rice (shrimp, chicken, ham) + Fries + 1 Grilled rib',
    'prod.combo10.name': 'Combo #10',
    'prod.combo10.desc': 'Special fried rice (shrimp, chicken, ham) + 1 Veggie lumpia + 6 Salt pepper ribs',
    'prod.combo11.name': 'Combo #11',
    'prod.combo11.desc': 'Special fried rice (shrimp, chicken, ham) + Fries + 6 Salt pepper ribs',
    'prod.combo12.name': 'Combo #12',
    'prod.combo12.desc': 'Special fried rice (shrimp, chicken, ham) + Sweet sour chicken (3 pcs) + 3 Salt pepper ribs',
    'prod.combo13.name': 'Combo #13',
    'prod.combo13.desc': 'Special fried rice (shrimp, chicken, ham) + Sweet sour chicken (6 pcs) + Special chopsuey',
    'prod.combo14.name': 'Combo #14',
    'prod.combo14.desc': 'Special fried rice (shrimp, chicken, ham) + Sweet sour chicken (6 pcs) + 1 Veggie lumpia',
    'prod.combo15.name': 'Combo #15',
    'prod.combo15.desc': 'Special fried rice (shrimp, chicken, ham) + 1 Grilled rib + 1 Veggie lumpia',
    'prod.combo16.name': 'Combo #16',
    'prod.combo16.desc': 'Special fried rice (shrimp, chicken, ham) + Fries + Special chopsuey',
    'prod.combo17.name': 'Combo #17',
    'prod.combo17.desc': 'Special fried rice (shrimp, chicken, ham) + Sweet sour chicken (3 pcs) + 1 Grilled rib',
    'prod.combo18.name': 'Combo #18',
    'prod.combo18.desc': 'Special fried rice (shrimp, chicken, ham) + Fries + 1 Veggie lumpia',
    'prod.combo19.name': 'Combo #19',
    'prod.combo19.desc': 'Half special fried rice (shrimp, chicken, ham) + Special chopsuey',
    'prod.combo20.name': 'Combo #20',
    'prod.combo20.desc': 'Half special fried rice (shrimp, chicken, ham) + 3 sweet sour chicken portions',
    'prod.combo21.name': 'Combo #21',
    'prod.combo21.desc': 'Half special fried rice (shrimp, chicken, ham) + 1 fried chicken',
    'prod.combo22.name': 'Combo #22',
    'prod.combo22.desc': 'Special fried rice (shrimp, chicken, ham) + 2 fried chicken + Fries or Special chopsuey',
    'prod.combo23.name': 'Combo #23',
    'prod.combo23.desc': 'Fried rice + Pineapple chicken + Fries or Chopsuey',
    'prod.combo24.name': 'Combo #24',
    'prod.combo24.desc': 'Fried rice + Sesame chicken + Fries or Chopsuey',
    'prod.esp1.name': 'Special fried rice',
    'prod.esp1.desc': 'Special fried rice (shrimp, chicken, ham)',
    'prod.esp2.name': 'Half special fried rice',
    'prod.esp2.desc': 'Half special fried rice (shrimp, chicken, ham)',
    'prod.esp3.name': 'Special chopsuey',
    'prod.esp3.desc': 'Special chopsuey (shrimp, chicken, ham)',
    'prod.esp4.name': 'Half special chopsuey',
    'prod.esp4.desc': 'Half special chopsuey (shrimp, chicken, ham)',
    'prod.rac1.name': 'Chicken with vegetables',
    'prod.rac1.desc': 'Chicken with vegetables (120 gr)',
    'prod.rac2.name': 'Sweet sour chicken',
    'prod.rac2.desc': 'Sweet sour chicken (15 pcs)',
    'prod.rac3.name': 'Honey sesame chicken',
    'prod.rac3.desc': 'Honey sesame chicken (15 pcs)',
    'prod.rac4.name': 'Salt pepper ribs',
    'prod.rac4.desc': 'Salt pepper ribs (320 gr)',
    'prod.rac5.name': 'Grilled ribs',
    'prod.rac5.desc': 'Grilled ribs (4 pcs)',
    'prod.rac6.name': 'Salt pepper shrimp',
    'prod.rac6.desc': 'Salt pepper shrimp (30/40 pcs approx)',
    'prod.rac7.name': 'Noodles',
    'prod.rac7.desc': 'Noodles (shrimp, chicken, ham)',
    'prod.rac8.name': 'Half noodles',
    'prod.rac8.desc': 'Half noodles (shrimp, chicken, ham)',
    'prod.ent1.name': 'French fries',
    'prod.ent1.desc': 'French fries portion (280 gr)',
    'prod.ent2.name': 'Veggie lumpia',
    'prod.ent2.desc': 'Veggie lumpia (2 pcs)',
    'prod.beb1.name': 'Minalba Water 355 ml',
    'prod.beb1.desc': 'Minalba Water 355 ml',
    'prod.beb2.name': 'Minalba Water 600 ml',
    'prod.beb2.desc': 'Minalba Water 600 ml',
    'prod.beb3.name': 'Malta Bottle 250 ml',
    'prod.beb3.desc': 'Malta Bottle 250 ml',
    'prod.beb4.name': 'Malta Can 355 ml',
    'prod.beb4.desc': 'Malta Can 355 ml',
    'prod.beb5.name': 'Gatorade 500 ml',
    'prod.beb5.desc': 'Gatorade 500 ml',
    'prod.beb6.name': 'Lipton 500 ml',
    'prod.beb6.desc': 'Lipton 500 ml',
    'prod.beb7.name': 'Soda Can 355 ml',
    'prod.beb7.desc': 'Soda Can 355 ml',
    'prod.beb8.name': 'Soda 1 lt',
    'prod.beb8.desc': 'Soda 1 lt',
    'prod.beb9.name': 'Soda 1.5 lt',
    'prod.beb9.desc': 'Soda 1.5 lt',
    'prod.beb10.name': 'Soda 2 lt',
    'prod.beb10.desc': 'Soda 2 lt',
    'prod.beb11.name': 'Yukery 250 ml',
    'prod.beb11.desc': 'Yukery 250 ml',
    'rev.0.name': 'John Doe',
    'rev.0.body': 'The best Chinese food I have ever tried. The flavor is authentic and the portions are generous.',
    'rev.1.name': 'Maria Garcia',
    'rev.1.body': 'The service is incredibly fast. I ordered for home delivery and it arrived hot and fresh in 20 minutes.',
    'rev.2.name': 'Charles Smith',
    'rev.2.body': 'Excellent quality-price. The locations are very clean and the atmosphere is great for eating with friends.',
    'rev.3.name': 'Ann Lopez',
    'rev.3.body': 'I love the Orange chicken, it has the perfect texture. Definitely my favorite place for Sundays.',
    'legal.pageTitle': 'Legal Notice',
    'legal.metaDescription': 'Terms and Conditions and Privacy Policy of Wallace Panda Express.',
    'legal.backHome': 'Back to Home',
    'legal.title': 'Legal Notice',
    'legal.lastUpdated': 'Last updated: June 2026',
    'legal.nav.terms': 'Terms',
    'legal.nav.privacy': 'Privacy',
    'legal.terms.title': 'Terms and Conditions',
    'legal.terms.s1.title': '1. Acceptance of Terms',
    'legal.terms.s1.text': 'By accessing and using the Wallace Panda Express online ordering platform, you accept these Terms and Conditions in their entirety. If you do not agree with any of these terms, we recommend that you do not use our service.',
    'legal.terms.s2.title': '2. Description of Service',
    'legal.terms.s2.p1': 'Wallace Panda Express provides you with a digital platform that allows you to place food orders for delivery or pickup at any of our locations located in Valencia, Naguanagua and San Diego.',
    'legal.terms.s2.p2': 'The ordering process is carried out through our web application and confirmed via WhatsApp. Wallace Panda Express does not process payments directly through the platform; payment is arranged directly with the location at the time of delivery or pickup.',
    'legal.terms.s3.title': '3. Orders and Payments',
    'legal.terms.s3.p1': 'By placing an order through our platform, you declare:',
    'legal.terms.s3.li1': 'That the information provided (name, address, phone) is truthful and up to date.',
    'legal.terms.s3.li2': 'That prices are expressed in US Dollars (USD). The total amount is calculated at the BCV (Banco Central de Venezuela) exchange rate in effect on the day of the order.',
    'legal.terms.s3.li3': 'That applicable taxes are included in the total shown at the time of ordering.',
    'legal.terms.s3.li4': 'That the delivery cost, when applicable, is indicated before confirming the order.',
    'legal.terms.s4.title': '4. Delivery and Pickup',
    'legal.terms.s4.p1': 'Delivery times are estimates and may vary depending on location, demand and weather conditions. Wallace Panda Express does not guarantee exact delivery times.',
    'legal.terms.s4.p2': 'The customer is responsible for providing an accurate and accessible delivery address. If the address is not within the coverage area of the location, the order cannot be processed for delivery.',
    'legal.terms.s5.title': '5. Cancellations and Refunds',
    'legal.terms.s5.p1': 'Once the order is confirmed via WhatsApp, cancellations must be managed by contacting the corresponding location as soon as possible.',
    'legal.terms.s5.p2': 'No refunds are made under any circumstances. Once the order is confirmed, the amount paid is non-refundable. It is the customer\'s responsibility to verify their order before confirming.',
    'legal.terms.s6.title': '6. User Obligations',
    'legal.terms.s6.p1': 'By using our service, the user agrees to:',
    'legal.terms.s6.li1': 'Provide truthful and complete information when placing orders.',
    'legal.terms.s6.li2': 'Not use the platform for illicit, fraudulent purposes or those that undermine the proper functioning of the service.',
    'legal.terms.s6.li3': 'Treat delivery and location staff with respect.',
    'legal.terms.s7.title': '7. Intellectual Property',
    'legal.terms.s7.text': 'All content on this platform, including but not limited to text, graphics, logos, images, videos, menu design and software, is the property of Wallace Panda Express and is protected by applicable intellectual property laws. Reproduction, distribution or modification without express authorization is prohibited.',
    'legal.terms.s8.title': '8. Limitation of Liability',
    'legal.terms.s8.p1': 'Wallace Panda Express is not responsible for allergic reactions or adverse effects derived from the consumption of our products. It is the customer\'s responsibility to inform about any allergy or dietary restriction when placing the order.',
    'legal.terms.s8.p2': 'We are not responsible for service interruptions due to technical failures, system maintenance, force majeure or circumstances beyond our reasonable control.',
    'legal.terms.s9.title': '9. Changes to Terms',
    'legal.terms.s9.text': 'Wallace Panda Express reserves the right to modify these Terms and Conditions at any time. Changes will take effect immediately after their publication on this page. Continued use of the platform after changes constitutes acceptance of them.',
    'legal.terms.s10.title': '10. Contact',
    'legal.terms.s10.text': 'If you have questions or concerns about these Terms and Conditions, you can contact us through our official WhatsApp channels or by visiting any of our locations.',
    'legal.privacy.title': 'Privacy Policy',
    'legal.privacy.s1.title': '1. Information We Collect',
    'legal.privacy.s1.p1': 'To process your orders and improve our service, we collect the following information:',
    'legal.privacy.s1.li1': 'Full name when placing an order.',
    'legal.privacy.s1.li2': 'Contact phone number (WhatsApp).',
    'legal.privacy.s1.li3': 'Delivery address and geographic location data when using the map.',
    'legal.privacy.s1.li4': 'Special instructions or additional notes provided voluntarily.',
    'legal.privacy.s2.title': '2. Use of Information',
    'legal.privacy.s2.p1': 'We use your information exclusively to:',
    'legal.privacy.s2.li1': 'Process and deliver your order efficiently.',
    'legal.privacy.s2.li2': 'Communicate with you regarding your order via WhatsApp.',
    'legal.privacy.s2.li3': 'Improve the quality of our service and user experience.',
    'legal.privacy.s3.title': '3. Sharing Your Information',
    'legal.privacy.s3.p1': 'Your personal information is shared only with the Wallace Panda Express location that will process your order. We do not sell, rent or share your information with third parties for marketing or advertising purposes.',
    'legal.privacy.s3.p2': 'We may disclose your information only when required by law or by order of competent authorities.',
    'legal.privacy.s4.title': '4. Data Security',
    'legal.privacy.s4.text': 'We implement technical and organizational security measures to protect your personal information against unauthorized access, alteration, disclosure or destruction. However, no method of Internet transmission or electronic storage is 100% secure, so we cannot guarantee absolute security.',
    'legal.privacy.s5.title': '5. Cookies and Tracking Technology',
    'legal.privacy.s5.text': 'Our platform may use cookies and similar technologies to improve your browsing experience, remember your preferences and analyze service usage. You can configure your browser to reject cookies, although this could affect the functioning of the platform.',
    'legal.privacy.s6.title': '6. Your Rights',
    'legal.privacy.s6.p1': 'You have the right to:',
    'legal.privacy.s6.li1': 'Request access to the personal information we have about you.',
    'legal.privacy.s6.li2': 'Request correction of inaccurate or outdated data.',
    'legal.privacy.s6.li3': 'Request deletion of your personal information from our records.',
    'legal.privacy.s7.title': '7. Minors',
    'legal.privacy.s7.text': 'Our service is not directed at minors under 18 years of age. We do not intentionally collect personal information from minors. If you are a parent or guardian and know that your child has provided us with personal information, contact us so we can delete it.',
    'legal.privacy.s8.title': '8. Changes to this Policy',
    'legal.privacy.s8.text': 'Wallace Panda Express reserves the right to update this Privacy Policy at any time. Changes will be published on this page with the date of the last update. We recommend reviewing this policy periodically.',
    'legal.privacy.s9.title': '9. Contact',
    'legal.privacy.s9.text': 'For inquiries about this Privacy Policy or about the processing of your personal data, you can contact us through our official WhatsApp channels or by visiting any of our locations.',
  },
  zh: {
    'nav.about': '关于我们',
    'nav.featured': '特色菜肴',
    'nav.locations': '分店',
    'nav.reviews': '评价',
    'nav.socials': '社交媒体',
    'nav.orderNow': '立即下单',
    'nav.home': '首页',
    'nav.menu': '菜单',
    'hero.tagline': '美味佳肴，直达餐桌！',
    'hero.cta': '开始下单',
    'about.title': '关于我们',
    'about.default': '在熊猫快餐，我们致力于提供最佳的餐饮体验。每一份订单都保证新鲜、高质量和我们独特的风味。',
    'featured.badge': '熊猫推荐',
    'featured.title': '精选菜品',
    'featured.viewAll': '查看全部菜单',
    'locations.badge': '找到我们',
    'locations.title': '我们的分店',
    'locations.open': '正在营业',
    'locations.closed': '休息中',
    'locations.closedToday': '今日休息',
    'reviews.badge': '熊猫社区',
    'reviews.title': '客户评价',
    'socials.title': '加入我们的大家庭！',
    'socials.tagline': '关注我们的社交网络，不错过任何促销活动和专属抽奖。',
    'cta.title': '饿了吗？',
    'cta.button': '查看完整菜单',
    'menu.welcome': '用餐愉快！',
    'menu.empty': '此处没有产品',
    'menu.ready': '准备下单',
    'menu.viewCart': '查看购物车',
    'menu.total': '总计',
    'menu.price': '价格',
    'menu.outOfStock': '已售罄',
    'cart.title': '您的订单',
    'cart.checkout': '结算',
    'cart.empty': '购物车是空的',
    'cart.emptyTagline': '添加一些美味的东西开始吧！',
    'cart.specialInstructions': '有什么特殊要求吗？',
    'cart.delivery': 'Delivery',
    'cart.fullName': '姓名',
    'cart.whatsapp': '联系电话',
    'cart.address': '详细送货地址',
    'cart.mapSelect': '在地图上选择',
    'cart.reference': '参考地点（房子颜色、附近商店...）',
    'cart.mapTitle': '送货位置',
    'cart.mapTagline': '将地图拖动到您的门前',
    'cart.closeMap': '关闭地图',
    'cart.shipping': '配送费',
    'cart.orderTotal': '订单总计',
    'cart.inBolivares': '玻利瓦尔金额',
    'cart.continue': '继续结算',
    'cart.back': '返回',
    'cart.confirmWhatsApp': '通过WhatsApp下单',
    'cart.mapHint': '点击地图设置您的位置',
    'cart.useLocation': '使用我的当前位置',
    'cart.locating': '正在定位...',
    'cart.error.nameMin': '姓名至少需要2个字符',
    'cart.error.phoneInvalid': '无效的电话号码',
    'cart.error.addressMin': '地址太短',
    'cart.error.addressOutOfRange': '地址超出配送范围',
    'cart.error.unknown': '未知错误',
    'cart.outOfCoverage': '超出范围',
    'cart.closed': '已关闭',
    'welcome.greeting': '欢迎光临！',
    'welcome.selectLocation': '选择您喜欢的分店',
    'welcome.noLocations': '目前没有可用的分店',
    'welcome.admin': '系统配置',
    'cat.combos': '套餐',
    'cat.especiales': '特色',
    'cat.raciones': '份量',
    'cat.entradas': '开胃菜',
    'cat.bebidas': '饮料',
    'loc.prebo.name': 'Prebo',
    'loc.prebo.address': '瓦伦西亚，安德烈斯·埃洛伊·布兰科大道',
    'loc.naguanagua.name': 'Naguanagua',
    'loc.naguanagua.address': 'Naguanagua，La Granja 购物中心',
    'loc.san-diego.name': 'San Diego',
    'loc.san-diego.address': '圣地亚哥，唐·朱利奥·森特诺大道',
    'prod.combo1.name': '套餐 #1',
    'prod.combo1.desc': '熊猫炸鸡(3块) + 薯条或特色杂碎',
    'prod.combo2.name': '套餐 #2',
    'prod.combo2.desc': '熊猫炸鸡(6块) + 薯条或特色杂碎',
    'prod.combo3.name': '套餐 #3',
    'prod.combo3.desc': '熊猫炸鸡(12块) + 薯条或特色杂碎',
    'prod.combo4.name': '套餐 #4',
    'prod.combo4.desc': '熊猫炸鸡(6块) + 特色杂碎 + 2春卷 + 4咕噜鸡 + 薯条',
    'prod.combo5.name': '套餐 #5',
    'prod.combo5.desc': '特色炒饭(虾,鸡肉,火腿) + 6咕噜鸡 + 薯条',
    'prod.combo6.name': '套餐 #6',
    'prod.combo6.desc': '特色炒饭(虾,鸡肉,火腿) + 特色杂碎 + 6椒盐排骨',
    'prod.combo7.name': '套餐 #7',
    'prod.combo7.desc': '特色炒饭(虾,鸡肉,火腿) + 特色杂碎 + 1春卷',
    'prod.combo8.name': '套餐 #8',
    'prod.combo8.desc': '特色炒饭(虾,鸡肉,火腿) + 特色杂碎 + 1烤排骨',
    'prod.combo9.name': '套餐 #9',
    'prod.combo9.desc': '特色炒饭(虾,鸡肉,火腿) + 薯条 + 1烤排骨',
    'prod.combo10.name': '套餐 #10',
    'prod.combo10.desc': '特色炒饭(虾,鸡肉,火腿) + 1春卷 + 6椒盐排骨',
    'prod.combo11.name': '套餐 #11',
    'prod.combo11.desc': '特色炒饭(虾,鸡肉,火腿) + 薯条 + 6椒盐排骨',
    'prod.combo12.name': '套餐 #12',
    'prod.combo12.desc': '特色炒饭(虾,鸡肉,火腿) + 咕噜鸡(3块) + 3椒盐排骨',
    'prod.combo13.name': '套餐 #13',
    'prod.combo13.desc': '特色炒饭(虾,鸡肉,火腿) + 咕噜鸡(6块) + 特色杂碎',
    'prod.combo14.name': '套餐 #14',
    'prod.combo14.desc': '特色炒饭(虾,鸡肉,火腿) + 咕噜鸡(6块) + 1春卷',
    'prod.combo15.name': '套餐 #15',
    'prod.combo15.desc': '特色炒饭(虾,鸡肉,火腿) + 1烤排骨 + 1春卷',
    'prod.combo16.name': '套餐 #16',
    'prod.combo16.desc': '特色炒饭(虾,鸡肉,火腿) + 薯条 + 特色杂碎',
    'prod.combo17.name': '套餐 #17',
    'prod.combo17.desc': '特色炒饭(虾,鸡肉,火腿) + 咕噜鸡(3块) + 1烤排骨',
    'prod.combo18.name': '套餐 #18',
    'prod.combo18.desc': '特色炒饭(虾,鸡肉,火腿) + 薯条 + 1春卷',
    'prod.combo19.name': '套餐 #19',
    'prod.combo19.desc': '半份特色炒饭(虾,鸡肉,火腿) + 特色杂碎',
    'prod.combo20.name': '套餐 #20',
    'prod.combo20.desc': '半份特色炒饭(虾,鸡肉,火腿) + 3份咕噜鸡',
    'prod.combo21.name': '套餐 #21',
    'prod.combo21.desc': '半份特色炒饭(虾,鸡肉,火腿) + 1炸鸡',
    'prod.combo22.name': '套餐 #22',
    'prod.combo22.desc': '特色炒饭(虾,鸡肉,火腿) + 2炸鸡 + 薯条或特色杂碎',
    'prod.combo23.name': '套餐 #23',
    'prod.combo23.desc': '炒饭 + 菠萝鸡 + 薯条或杂碎',
    'prod.combo24.name': '套餐 #24',
    'prod.combo24.desc': '炒饭 + 芝麻鸡 + 薯条或杂碎',
    'prod.esp1.name': '特色炒饭',
    'prod.esp1.desc': '特色炒饭(虾,鸡肉,火腿)',
    'prod.esp2.name': '半份特色炒饭',
    'prod.esp2.desc': '半份特色炒饭(虾,鸡肉,火腿)',
    'prod.esp3.name': '特色杂碎',
    'prod.esp3.desc': '特色杂碎(虾,鸡肉,火腿)',
    'prod.esp4.name': '半份特色杂碎',
    'prod.esp4.desc': '半份特色杂碎(虾,鸡肉,火腿)',
    'prod.rac1.name': '蔬菜鸡肉',
    'prod.rac1.desc': '蔬菜鸡肉(120克)',
    'prod.rac2.name': '咕噜鸡',
    'prod.rac2.desc': '咕噜鸡(15块)',
    'prod.rac3.name': '蜂蜜芝麻鸡',
    'prod.rac3.desc': '蜂蜜芝麻鸡(15块)',
    'prod.rac4.name': '椒盐排骨',
    'prod.rac4.desc': '椒盐排骨(320克)',
    'prod.rac5.name': '烤排骨',
    'prod.rac5.desc': '烤排骨(4块)',
    'prod.rac6.name': '椒盐虾',
    'prod.rac6.desc': '椒盐虾(30/40只)',
    'prod.rac7.name': '炒面',
    'prod.rac7.desc': '炒面(虾,鸡肉,火腿)',
    'prod.rac8.name': '半份炒面',
    'prod.rac8.desc': '半份炒面(虾,鸡肉,火腿)',
    'prod.ent1.name': '薯条',
    'prod.ent1.desc': '薯条(280克)',
    'prod.ent2.name': '春卷',
    'prod.ent2.desc': '春卷(2块)',
    'prod.beb1.name': 'Minalba水 355ml',
    'prod.beb1.desc': 'Minalba水 355ml',
    'prod.beb2.name': 'Minalba水 600ml',
    'prod.beb2.desc': 'Minalba水 600ml',
    'prod.beb3.name': 'Malta瓶装 250ml',
    'prod.beb3.desc': 'Malta瓶装 250ml',
    'prod.beb4.name': 'Malta罐装 355ml',
    'prod.beb4.desc': 'Malta罐装 355ml',
    'prod.beb5.name': 'Gatorade 500ml',
    'prod.beb5.desc': 'Gatorade 500ml',
    'prod.beb6.name': 'Lipton 500ml',
    'prod.beb6.desc': 'Lipton 500ml',
    'prod.beb7.name': '汽水罐装 355ml',
    'prod.beb7.desc': '汽水罐装 355ml',
    'prod.beb8.name': '汽水 1升',
    'prod.beb8.desc': '汽水 1升',
    'prod.beb9.name': '汽水 1.5升',
    'prod.beb9.desc': '汽水 1.5升',
    'prod.beb10.name': '汽水 2升',
    'prod.beb10.desc': '汽水 2升',
    'prod.beb11.name': 'Yukery 250ml',
    'prod.beb11.desc': 'Yukery 250ml',
    'rev.0.name': '张三',
    'rev.0.body': '我尝试过的最好的中餐。味道地道，分量足。',
    'rev.1.name': '李四',
    'rev.1.body': '服务非常快。我订了外卖，20分钟就送到，又热又新鲜。',
    'rev.2.name': '王五',
    'rev.2.body': '物美价廉。分店非常干净，环境非常适合和朋友一起吃饭。',
    'rev.3.name': '赵六',
    'rev.3.body': '我爱陈皮鸡，它的质地完美。绝对是我周日最喜欢去的地方。',
    'legal.pageTitle': '法律声明',
    'legal.metaDescription': 'Wallace Panda Express 的条款和条件以及隐私政策。',
    'legal.backHome': '返回首页',
    'legal.title': '法律声明',
    'legal.lastUpdated': '最后更新：2026年6月',
    'legal.nav.terms': '条款',
    'legal.nav.privacy': '隐私',
    'legal.terms.title': '条款和条件',
    'legal.terms.s1.title': '1. 接受条款',
    'legal.terms.s1.text': '访问和使用 Wallace Panda Express 在线订购平台即表示您完全接受这些条款和条件。如果您不同意其中任何条款，建议您不要使用我们的服务。',
    'legal.terms.s2.title': '2. 服务描述',
    'legal.terms.s2.p1': 'Wallace Panda Express 为您提供一个数字平台，允许您在 Valencia、Naguanagua 和 San Diego 的任何门店下单订餐，支持配送或自取。',
    'legal.terms.s2.p2': '订购流程通过我们的网络应用程序完成，并通过 WhatsApp 确认。Wallace Panda Express 不直接通过平台处理付款；付款在配送或自取时与门店直接协商。',
    'legal.terms.s3.title': '3. 订单和付款',
    'legal.terms.s3.p1': '通过我们的平台下单时，您声明：',
    'legal.terms.s3.li1': '提供的信息（姓名、地址、电话）真实且是最新的。',
    'legal.terms.s3.li2': '价格以美元（USD）表示。总金额按订单当日委内瑞拉中央银行（BCV）的汇率计算。',
    'legal.terms.s3.li3': '适用税款已包含在下单时显示的总额中。',
    'legal.terms.s3.li4': '配送费用（如适用）在确认订单前已注明。',
    'legal.terms.s4.title': '4. 配送和自取',
    'legal.terms.s4.p1': '配送时间为估计值，可能因位置、需求和天气条件而异。Wallace Panda Express 不保证确切的配送时间。',
    'legal.terms.s4.p2': '客户有责任提供准确且可到达的配送地址。如果地址不在门店的配送范围内，则无法处理配送订单。',
    'legal.terms.s5.title': '5. 取消和退款',
    'legal.terms.s5.p1': '订单通过 WhatsApp 确认后，取消必须尽快联系相应门店处理。',
    'legal.terms.s5.p2': '任何情况下均不退款。订单确认后，已支付金额不可退还。客户有责任在确认前核实订单。',
    'legal.terms.s6.title': '6. 用户义务',
    'legal.terms.s6.p1': '使用我们的服务即表示用户同意：',
    'legal.terms.s6.li1': '下单时提供真实完整的信息。',
    'legal.terms.s6.li2': '不将平台用于非法、欺诈目的或破坏服务正常运行的行为。',
    'legal.terms.s6.li3': '以尊重态度对待配送和门店工作人员。',
    'legal.terms.s7.title': '7. 知识产权',
    'legal.terms.s7.text': '本平台上的所有内容，包括但不限于文本、图形、徽标、图像、视频、菜单设计和软件，均为 Wallace Panda Express 的财产，受适用知识产权法保护。未经明确授权，禁止复制、分发或修改。',
    'legal.terms.s8.title': '8. 责任限制',
    'legal.terms.s8.p1': 'Wallace Panda Express 对因食用我们产品引起的过敏反应或不良后果不承担责任。客户有责任在下单时告知任何过敏或饮食限制。',
    'legal.terms.s8.p2': '我们对因技术故障、系统维护、不可抗力或超出我们合理控制范围的情况导致的服务中断不承担责任。',
    'legal.terms.s9.title': '9. 条款变更',
    'legal.terms.s9.text': 'Wallace Panda Express 保留随时修改这些条款和条件的权利。更改将在本页面发布后立即生效。更改后继续使用平台即表示接受更改。',
    'legal.terms.s10.title': '10. 联系方式',
    'legal.terms.s10.text': '如果您对这些条款和条件有任何疑问或疑虑，可以通过我们的官方 WhatsApp 渠道或访问我们的任何门店联系我们。',
    'legal.privacy.title': '隐私政策',
    'legal.privacy.s1.title': '1. 我们收集的信息',
    'legal.privacy.s1.p1': '为处理您的订单并改进我们的服务，我们收集以下信息：',
    'legal.privacy.s1.li1': '下单时的全名。',
    'legal.privacy.s1.li2': '联系电话（WhatsApp）。',
    'legal.privacy.s1.li3': '配送地址和使用地图时的地理位置数据。',
    'legal.privacy.s1.li4': '自愿提供的特殊说明或附加备注。',
    'legal.privacy.s2.title': '2. 信息使用',
    'legal.privacy.s2.p1': '我们 exclusively 使用您的信息用于：',
    'legal.privacy.s2.li1': '高效处理和配送您的订单。',
    'legal.privacy.s2.li2': '通过 WhatsApp 与您沟通订单相关事宜。',
    'legal.privacy.s2.li3': '提高服务质量和用户体验。',
    'legal.privacy.s3.title': '3. 共享您的信息',
    'legal.privacy.s3.p1': '您的个人信息仅与将处理您订单的 Wallace Panda Express 门店共享。我们不出售、出租或将您的信息分享给第三方用于营销或广告目的。',
    'legal.privacy.s3.p2': '我们仅在法律要求或主管当局命令时才披露您的信息。',
    'legal.privacy.s4.title': '4. 数据安全',
    'legal.privacy.s4.text': '我们实施技术和组织安全措施，保护您的个人信息免受未经授权的访问、更改、披露或销毁。但是，没有任何互联网传输或电子存储方法是 100% 安全的，因此我们无法保证绝对安全。',
    'legal.privacy.s5.title': '5. Cookie 和跟踪技术',
    'legal.privacy.s5.text': '我们的平台可能使用 Cookie 和类似技术来改善您的浏览体验、记住您的偏好并分析服务使用情况。您可以配置浏览器拒绝 Cookie，但这可能会影响平台的功能。',
    'legal.privacy.s6.title': '6. 您的权利',
    'legal.privacy.s6.p1': '您有权：',
    'legal.privacy.s6.li1': '请求访问我们持有的关于您的个人信息。',
    'legal.privacy.s6.li2': '请求更正不准确或过时的数据。',
    'legal.privacy.s6.li3': '请求从我们的记录中删除您的个人信息。',
    'legal.privacy.s7.title': '7. 未成年人',
    'legal.privacy.s7.text': '我们的服务不面向 18 岁以下的未成年人。我们不故意收集未成年人的个人信息。如果您是父母或监护人，并且知道您的孩子向我们提供了个人信息，请联系我们以便我们删除。',
    'legal.privacy.s8.title': '8. 政策变更',
    'legal.privacy.s8.text': 'Wallace Panda Express 保留随时更新此隐私政策的权利。更改将在本页面上发布，并注明最后更新日期。我们建议定期查看此政策。',
    'legal.privacy.s9.title': '9. 联系方式',
    'legal.privacy.s9.text': '有关此隐私政策或个人数据处理的咨询，可以通过我们的官方 WhatsApp 渠道或访问我们的任何门店联系我们。',
  }
};
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);
export function LanguageProvider({ children }: { children: ReactNode }) { const [language, setLanguage] = useState<Language>('es');
const t = (key: string) => { return translations[language][key] || key; }; return ( <LanguageContext.Provider value={{ language, setLanguage, t }}> {children} </LanguageContext.Provider> );}

export function useLanguage() { const context = useContext(LanguageContext);
if (context === undefined) { throw new Error('useLanguage must be used within a LanguageProvider'); }
return context;}
