import React, { createContext, useContext, useState, ReactNode } from 'react';
export type Language = 'es' | 'en' | 'zh';
interface LanguageContextType { language: Language; setLanguage: (lang: Language) => void; t: (key: string) => string;}

const translations: Record<Language, Record<string, string>> = {
  es: {
    'nav.about': 'Sobre Nosotros',
    'nav.featured': 'Platos',
    'nav.locations': 'Sedes',
    'nav.reviews': 'Reseñas',
    'nav.socials': 'Redes',
    'nav.orderNow': 'Pedir Ahora',
    'nav.home': 'Inicio',
    'nav.menu': 'Menú',
    'hero.tagline': '¡LA MEJOR COMIDA DIRECTA A TU MESA!',
    'hero.cta': 'Hacer Pedido',
    'about.title': 'Sobre Nosotros',
    'about.default': 'En Panda Express, nos apasiona brindar la mejor experiencia gastronómica. Frescura, calidad y el sabor que nos caracteriza en cada pedido.',
    'featured.badge': 'Favoritos del Panda',
    'featured.title': 'Platos Destacados',
    'featured.viewAll': 'Ver todo el menú',
    'locations.badge': 'Encuéntranos',
    'locations.title': 'Nuestras Sedes',
    'locations.open': 'Abierto Ahora',
    'locations.closed': 'Cerrado',
    'reviews.badge': 'Comunidad Panda',
    'reviews.title': 'Lo que dicen nuestros clientes',
    'socials.title': '¡Únete a la familia!',
    'socials.tagline': 'Síguenos en nuestras redes para no perderte ninguna promoción bomba y sorteos exclusivos.',
    'cta.title': '¿Con hambre?',
    'cta.button': 'Ver Menú Completo',
    'menu.welcome': '¡Buen provecho!',
    'menu.empty': 'No hay productos aquí',
    'menu.ready': 'Listo para pedir',
    'menu.viewCart': 'Ver Carrito',
    'menu.total': 'Total',
    'menu.price': 'Precio',
    'menu.outOfStock': 'Agotado',
    'cart.title': 'Tu Pedido',
    'cart.checkout': 'Finalizar Pago',
    'cart.empty': 'Tu carrito está vacío',
    'cart.emptyTagline': '¡Agrega algo delicioso para comenzar!',
    'cart.specialInstructions': '¿Alguna instrucción especial?',
    'cart.delivery': 'Delivery',
    'cart.fullName': 'Nombre completo',
    'cart.whatsapp': 'WhatsApp de contacto',
    'cart.address': 'Dirección exacta de entrega',
    'cart.mapSelect': 'Seleccionar en el mapa',
    'cart.reference': 'Punto de referencia (Color de casa, local cercano...)',
    'cart.mapTitle': 'Ubicación de entrega',
    'cart.mapTagline': 'Arrastra el mapa hasta tu puerta',
    'cart.closeMap': 'Cerrar Mapa',
    'cart.shipping': 'Costo de Envío',
    'cart.orderTotal': 'Total del Pedido',
    'cart.inBolivares': 'En Bolívares',
    'cart.continue': 'Continuar al Pago',
    'cart.back': 'Volver',
    'cart.confirmWhatsApp': 'Pedir por WhatsApp',
    'cart.mapHint': 'Toca el mapa para fijar tu ubicación',
    'cart.useLocation': 'Usar mi ubicación actual',
    'cart.locating': 'Localizando...',
    'welcome.greeting': '¡Bienvenido!',
    'welcome.selectLocation': 'Selecciona tu sede favorita',
    'welcome.noLocations': 'No hay sedes disponibles en este momento',
    'welcome.admin': 'Configuración del Sistema',
    'cat.combos': 'Combos',
    'cat.especiales': 'Especiales',
    'cat.raciones': 'Raciones',
    'cat.entradas': 'Entradas',
    'cat.bebidas': 'Bebidas',
    'loc.prebo.name': 'Prebo',
    'loc.prebo.address': 'Av. Andrés Eloy Blanco, Valencia',
    'loc.naguanagua.name': 'Naguanagua',
    'loc.naguanagua.address': 'CC La Granja, Naguanagua',
    'loc.san-diego.name': 'San Diego',
    'loc.san-diego.address': 'Av. Don Julio Centeno, San Diego',
    'prod.combo1.name': 'Combo #1',
    'prod.combo1.desc': 'Pollo frito Panda (3 piezas) + Papas fritas o Chopsuey especial',
    'prod.combo2.name': 'Combo #2',
    'prod.combo2.desc': 'Pollo frito Panda (6 piezas) + Papas fritas o Chopsuey especial',
    'prod.combo3.name': 'Combo #3',
    'prod.combo3.desc': 'Pollo frito Panda (12 piezas) + Papas fritas o Chopsuey especial',
    'prod.combo4.name': 'Combo #4',
    'prod.combo4.desc': 'Pollo frito Panda (6 piezas) + Chopsuey especial + 2 Lumpia vegetales + 4 Pollo agridulce + Papas fritas',
    'prod.combo5.name': 'Combo #5',
    'prod.combo5.desc': 'Arroz frito especial (camarón, pollo y jamón) + 6 Pollo agridulce + Papas fritas',
    'prod.combo6.name': 'Combo #6',
    'prod.combo6.desc': 'Arroz frito especial (camarón, pollo y jamón) + Chopsuey especial + 6 Costilla sal y pimienta',
    'prod.combo7.name': 'Combo #7',
    'prod.combo7.desc': 'Arroz frito especial (camarón, pollo y jamón) + Chopsuey especial + 1 Lumpia vegetales',
    'prod.combo8.name': 'Combo #8',
    'prod.combo8.desc': 'Arroz frito especial (camarón, pollo y jamón) + Chopsuey especial + 1 Costilla asada',
    'prod.combo9.name': 'Combo #9',
    'prod.combo9.desc': 'Arroz frito especial (camarón, pollo y jamón) + Papas fritas + 1 Costilla asada',
    'prod.combo10.name': 'Combo #10',
    'prod.combo10.desc': 'Arroz frito especial (camarón, pollo y jamón) + 1 Lumpia vegetales + 6 Costilla sal y pimienta',
    'prod.combo11.name': 'Combo #11',
    'prod.combo11.desc': 'Arroz frito especial (camarón, pollo y jamón) + Papas fritas + 6 Costilla sal y pimienta',
    'prod.combo12.name': 'Combo #12',
    'prod.combo12.desc': 'Arroz frito especial (camarón, pollo y jamón) + Pollo agridulce (3 piezas) + 3 Costilla sal y pimienta',
    'prod.combo13.name': 'Combo #13',
    'prod.combo13.desc': 'Arroz frito especial (camarón, pollo y jamón) + Pollo agridulce (6 piezas) + Chopsuey especial',
    'prod.combo14.name': 'Combo #14',
    'prod.combo14.desc': 'Arroz frito especial (camarón, pollo y jamón) + Pollo agridulce (6 piezas) + 1 Lumpia vegetales',
    'prod.combo15.name': 'Combo #15',
    'prod.combo15.desc': 'Arroz frito especial (camarón, pollo y jamón) + 1 Costilla asada + 1 Lumpia vegetales',
    'prod.combo16.name': 'Combo #16',
    'prod.combo16.desc': 'Arroz frito especial (camarón, pollo y jamón) + Papas fritas + Chopsuey especial',
    'prod.combo17.name': 'Combo #17',
    'prod.combo17.desc': 'Arroz frito especial (camarón, pollo y jamón) + Pollo agridulce (3 piezas) + 1 Costilla asada',
    'prod.combo18.name': 'Combo #18',
    'prod.combo18.desc': 'Arroz frito especial (camarón, pollo y jamón) + Papas fritas + 1 Lumpia vegetales',
    'prod.combo19.name': 'Combo #19',
    'prod.combo19.desc': 'Media ración arroz frito especial (camarón, pollo y jamón) + Chopsuey especial',
    'prod.combo20.name': 'Combo #20',
    'prod.combo20.desc': 'Media ración arroz frito especial (camarón, pollo y jamón) + 3 porciones pollo agridulce',
    'prod.combo21.name': 'Combo #21',
    'prod.combo21.desc': 'Media ración arroz frito especial (camarón, pollo y jamón) + 1 pollo frito',
    'prod.combo22.name': 'Combo #22',
    'prod.combo22.desc': 'Arroz frito especial (camarón, pollo y jamón) + 2 pollo frito + Papas fritas o Chopsuey especial',
    'prod.combo23.name': 'Combo #23',
    'prod.combo23.desc': 'Arroz frito + Pollo con piña + Papa o Chopsuey',
    'prod.combo24.name': 'Combo #24',
    'prod.combo24.desc': 'Arroz frito + Pollo ajonjolí + Papa o Chopsuey',
    'prod.esp1.name': 'Arroz frito especial',
    'prod.esp1.desc': 'Arroz frito especial (camarón, pollo y jamón)',
    'prod.esp2.name': 'Media arroz frito especial',
    'prod.esp2.desc': 'Media ración arroz frito especial (camarón, pollo y jamón)',
    'prod.esp3.name': 'Chopsuey especial',
    'prod.esp3.desc': 'Chopsuey especial (camarón, pollo y jamón)',
    'prod.esp4.name': 'Media Chopsuey especial',
    'prod.esp4.desc': 'Media ración Chopsuey especial (camarón, pollo y jamón)',
    'prod.rac1.name': 'Pollo con vegetales',
    'prod.rac1.desc': 'Pollo con vegetales (120 gr)',
    'prod.rac2.name': 'Pollo agridulce',
    'prod.rac2.desc': 'Pollo agridulce (15 und)',
    'prod.rac3.name': 'Pollo miel y ajonjolí',
    'prod.rac3.desc': 'Pollo miel y ajonjolí (15 und)',
    'prod.rac4.name': 'Costillas sal y pimienta',
    'prod.rac4.desc': 'Costillas sal y pimienta (320 gr)',
    'prod.rac5.name': 'Costillas asadas',
    'prod.rac5.desc': 'Costillas asadas (4 und)',
    'prod.rac6.name': 'Camarón sal y pimienta',
    'prod.rac6.desc': 'Camarón sal y pimienta (30/40 und aprox)',
    'prod.rac7.name': 'Tallarines',
    'prod.rac7.desc': 'Tallarines (camarón, pollo y jamón)',
    'prod.rac8.name': 'Media tallarines',
    'prod.rac8.desc': 'Media ración de tallarines (camarón, pollo y jamón)',
    'prod.ent1.name': 'Papas fritas',
    'prod.ent1.desc': 'Ración papas fritas (280 gr)',
    'prod.ent2.name': 'Lumpia de vegetales',
    'prod.ent2.desc': 'Ración lumpia de vegetales (2 und)',
    'prod.beb1.name': 'Agua Minalba 355 ml',
    'prod.beb1.desc': 'Agua Minalba 355 ml',
    'prod.beb2.name': 'Agua Minalba 600 ml',
    'prod.beb2.desc': 'Agua Minalba 600 ml',
    'prod.beb3.name': 'Botella de Malta 250 ml',
    'prod.beb3.desc': 'Botella de Malta 250 ml',
    'prod.beb4.name': 'Lata de Malta 355 ml',
    'prod.beb4.desc': 'Lata de Malta 355 ml',
    'prod.beb5.name': 'Gatorade 500 ml',
    'prod.beb5.desc': 'Gatorade 500 ml',
    'prod.beb6.name': 'Lipton 500 ml',
    'prod.beb6.desc': 'Lipton 500 ml',
    'prod.beb7.name': 'Lata de refresco 355 ml',
    'prod.beb7.desc': 'Lata de refresco 355 ml',
    'prod.beb8.name': 'Refresco 1 lt',
    'prod.beb8.desc': 'Refresco 1 lt',
    'prod.beb9.name': 'Refresco 1.5 lt',
    'prod.beb9.desc': 'Refresco 1.5 lt',
    'prod.beb10.name': 'Refresco 2 lt',
    'prod.beb10.desc': 'Refresco 2 lt',
    'prod.beb11.name': 'Yukery 250 ml',
    'prod.beb11.desc': 'Yukery 250 ml',
    'rev.0.name': 'Juan Pérez',
    'rev.0.body': 'La mejor comida china que he probado. El sabor es auténtico y las porciones son generosas.',
    'rev.1.name': 'Maria Garcia',
    'rev.1.body': 'El servicio es increíblemente rápido. Pedí a domicilio y llegó caliente y fresco en 20 minutos.',
    'rev.2.name': 'Carlos Ruiz',
    'rev.2.body': 'Excelente calidad-precio. Las sedes son muy limpias y el ambiente es genial para comer con amigos.',
    'rev.3.name': 'Ana Lopez',
    'rev.3.body': 'Amo el pollo agridulce, tiene la textura perfecta. Definitivamente mi lugar favorito para los domingos.',
  },
  en: {
    'nav.about': 'About Us',
    'nav.featured': 'Dishes',
    'nav.locations': 'Locations',
    'nav.reviews': 'Reviews',
    'nav.socials': 'Socials',
    'nav.orderNow': 'Order Now',
    'nav.home': 'Home',
    'nav.menu': 'Menu',
    'hero.tagline': 'THE BEST FOOD STRAIGHT TO YOUR TABLE!',
    'hero.cta': 'Place Order',
    'about.title': 'About Us',
    'about.default': 'At Panda Express, we are passionate about providing the best dining experience. Freshness, quality, and our characteristic flavor in every order.',
    'featured.badge': 'Panda Favorites',
    'featured.title': 'Featured Dishes',
    'featured.viewAll': 'View full menu',
    'locations.badge': 'Find Us',
    'locations.title': 'Our Locations',
    'locations.open': 'Open Now',
    'locations.closed': 'Closed',
    'locations.closedToday': 'Currently Closed',
    'reviews.badge': 'Panda Community',
    'reviews.title': 'What our customers say',
    'socials.title': 'Join the family!',
    'socials.tagline': 'Follow us on our networks to not miss any bomb promotions and exclusive giveaways.',
    'cta.title': 'Hungry?',
    'cta.button': 'View Full Menu',
    'menu.welcome': 'Enjoy your meal!',
    'menu.empty': 'No products here',
    'menu.ready': 'Ready to order',
    'menu.viewCart': 'View Cart',
    'menu.total': 'Total',
    'menu.price': 'Price',
    'menu.outOfStock': 'Out of Stock',
    'cart.title': 'Your Order',
    'cart.checkout': 'Checkout',
    'cart.empty': 'Your cart is empty',
    'cart.emptyTagline': 'Add something delicious to start!',
    'cart.specialInstructions': 'Any special instructions?',
    'cart.delivery': 'Delivery',
    'cart.fullName': 'Full name',
    'cart.whatsapp': 'Contact WhatsApp',
    'cart.address': 'Exact delivery address',
    'cart.mapSelect': 'Select on map',
    'cart.reference': 'Reference point (House color, nearby store...)',
    'cart.mapTitle': 'Delivery Location',
    'cart.mapTagline': 'Drag the map to your door',
    'cart.closeMap': 'Close Map',
    'cart.shipping': 'Shipping Fee',
    'cart.orderTotal': 'Order Total',
    'cart.inBolivares': 'In Bolivares',
    'cart.continue': 'Continue to Payment',
    'cart.back': 'Back',
    'cart.confirmWhatsApp': 'Order via WhatsApp',
    'cart.mapHint': 'Tap the map to set your location',
    'cart.useLocation': 'Use my current location',
    'cart.locating': 'Locating...',
    'welcome.greeting': 'Welcome!',
    'welcome.selectLocation': 'Select your favorite location',
    'welcome.noLocations': 'No locations available right now',
    'welcome.admin': 'System Configuration',
    'cat.combos': 'Combos',
    'cat.especiales': 'Special',
    'cat.raciones': 'Portions',
    'cat.entradas': 'Appetizers',
    'cat.bebidas': 'Drinks',
    'loc.prebo.name': 'Prebo',
    'loc.prebo.address': 'Andres Eloy Blanco Ave, Valencia',
    'loc.naguanagua.name': 'Naguanagua',
    'loc.naguanagua.address': 'La Granja Mall, Naguanagua',
    'loc.san-diego.name': 'San Diego',
    'loc.san-diego.address': 'Don Julio Centeno Ave, San Diego',
    'prod.combo1.name': 'Combo #1',
    'prod.combo1.desc': 'Panda fried chicken (3 pcs) + French fries or Special chopsuey',
    'prod.combo2.name': 'Combo #2',
    'prod.combo2.desc': 'Panda fried chicken (6 pcs) + French fries or Special chopsuey',
    'prod.combo3.name': 'Combo #3',
    'prod.combo3.desc': 'Panda fried chicken (12 pcs) + French fries or Special chopsuey',
    'prod.combo4.name': 'Combo #4',
    'prod.combo4.desc': 'Panda fried chicken (6 pcs) + Special chopsuey + 2 Veggie lumpia + 4 Sweet sour chicken + Fries',
    'prod.combo5.name': 'Combo #5',
    'prod.combo5.desc': 'Special fried rice (shrimp, chicken, ham) + 6 Sweet sour chicken + Fries',
    'prod.combo6.name': 'Combo #6',
    'prod.combo6.desc': 'Special fried rice (shrimp, chicken, ham) + Special chopsuey + 6 Salt pepper ribs',
    'prod.combo7.name': 'Combo #7',
    'prod.combo7.desc': 'Special fried rice (shrimp, chicken, ham) + Special chopsuey + 1 Veggie lumpia',
    'prod.combo8.name': 'Combo #8',
    'prod.combo8.desc': 'Special fried rice (shrimp, chicken, ham) + Special chopsuey + 1 Grilled rib',
    'prod.combo9.name': 'Combo #9',
    'prod.combo9.desc': 'Special fried rice (shrimp, chicken, ham) + Fries + 1 Grilled rib',
    'prod.combo10.name': 'Combo #10',
    'prod.combo10.desc': 'Special fried rice (shrimp, chicken, ham) + 1 Veggie lumpia + 6 Salt pepper ribs',
    'prod.combo11.name': 'Combo #11',
    'prod.combo11.desc': 'Special fried rice (shrimp, chicken, ham) + Fries + 6 Salt pepper ribs',
    'prod.combo12.name': 'Combo #12',
    'prod.combo12.desc': 'Special fried rice (shrimp, chicken, ham) + Sweet sour chicken (3 pcs) + 3 Salt pepper ribs',
    'prod.combo13.name': 'Combo #13',
    'prod.combo13.desc': 'Special fried rice (shrimp, chicken, ham) + Sweet sour chicken (6 pcs) + Special chopsuey',
    'prod.combo14.name': 'Combo #14',
    'prod.combo14.desc': 'Special fried rice (shrimp, chicken, ham) + Sweet sour chicken (6 pcs) + 1 Veggie lumpia',
    'prod.combo15.name': 'Combo #15',
    'prod.combo15.desc': 'Special fried rice (shrimp, chicken, ham) + 1 Grilled rib + 1 Veggie lumpia',
    'prod.combo16.name': 'Combo #16',
    'prod.combo16.desc': 'Special fried rice (shrimp, chicken, ham) + Fries + Special chopsuey',
    'prod.combo17.name': 'Combo #17',
    'prod.combo17.desc': 'Special fried rice (shrimp, chicken, ham) + Sweet sour chicken (3 pcs) + 1 Grilled rib',
    'prod.combo18.name': 'Combo #18',
    'prod.combo18.desc': 'Special fried rice (shrimp, chicken, ham) + Fries + 1 Veggie lumpia',
    'prod.combo19.name': 'Combo #19',
    'prod.combo19.desc': 'Half special fried rice (shrimp, chicken, ham) + Special chopsuey',
    'prod.combo20.name': 'Combo #20',
    'prod.combo20.desc': 'Half special fried rice (shrimp, chicken, ham) + 3 sweet sour chicken portions',
    'prod.combo21.name': 'Combo #21',
    'prod.combo21.desc': 'Half special fried rice (shrimp, chicken, ham) + 1 fried chicken',
    'prod.combo22.name': 'Combo #22',
    'prod.combo22.desc': 'Special fried rice (shrimp, chicken, ham) + 2 fried chicken + Fries or Special chopsuey',
    'prod.combo23.name': 'Combo #23',
    'prod.combo23.desc': 'Fried rice + Pineapple chicken + Fries or Chopsuey',
    'prod.combo24.name': 'Combo #24',
    'prod.combo24.desc': 'Fried rice + Sesame chicken + Fries or Chopsuey',
    'prod.esp1.name': 'Special fried rice',
    'prod.esp1.desc': 'Special fried rice (shrimp, chicken, ham)',
    'prod.esp2.name': 'Half special fried rice',
    'prod.esp2.desc': 'Half special fried rice (shrimp, chicken, ham)',
    'prod.esp3.name': 'Special chopsuey',
    'prod.esp3.desc': 'Special chopsuey (shrimp, chicken, ham)',
    'prod.esp4.name': 'Half special chopsuey',
    'prod.esp4.desc': 'Half special chopsuey (shrimp, chicken, ham)',
    'prod.rac1.name': 'Chicken with vegetables',
    'prod.rac1.desc': 'Chicken with vegetables (120 gr)',
    'prod.rac2.name': 'Sweet sour chicken',
    'prod.rac2.desc': 'Sweet sour chicken (15 pcs)',
    'prod.rac3.name': 'Honey sesame chicken',
    'prod.rac3.desc': 'Honey sesame chicken (15 pcs)',
    'prod.rac4.name': 'Salt pepper ribs',
    'prod.rac4.desc': 'Salt pepper ribs (320 gr)',
    'prod.rac5.name': 'Grilled ribs',
    'prod.rac5.desc': 'Grilled ribs (4 pcs)',
    'prod.rac6.name': 'Salt pepper shrimp',
    'prod.rac6.desc': 'Salt pepper shrimp (30/40 pcs approx)',
    'prod.rac7.name': 'Noodles',
    'prod.rac7.desc': 'Noodles (shrimp, chicken, ham)',
    'prod.rac8.name': 'Half noodles',
    'prod.rac8.desc': 'Half noodles (shrimp, chicken, ham)',
    'prod.ent1.name': 'French fries',
    'prod.ent1.desc': 'French fries portion (280 gr)',
    'prod.ent2.name': 'Veggie lumpia',
    'prod.ent2.desc': 'Veggie lumpia (2 pcs)',
    'prod.beb1.name': 'Minalba Water 355 ml',
    'prod.beb1.desc': 'Minalba Water 355 ml',
    'prod.beb2.name': 'Minalba Water 600 ml',
    'prod.beb2.desc': 'Minalba Water 600 ml',
    'prod.beb3.name': 'Malta Bottle 250 ml',
    'prod.beb3.desc': 'Malta Bottle 250 ml',
    'prod.beb4.name': 'Malta Can 355 ml',
    'prod.beb4.desc': 'Malta Can 355 ml',
    'prod.beb5.name': 'Gatorade 500 ml',
    'prod.beb5.desc': 'Gatorade 500 ml',
    'prod.beb6.name': 'Lipton 500 ml',
    'prod.beb6.desc': 'Lipton 500 ml',
    'prod.beb7.name': 'Soda Can 355 ml',
    'prod.beb7.desc': 'Soda Can 355 ml',
    'prod.beb8.name': 'Soda 1 lt',
    'prod.beb8.desc': 'Soda 1 lt',
    'prod.beb9.name': 'Soda 1.5 lt',
    'prod.beb9.desc': 'Soda 1.5 lt',
    'prod.beb10.name': 'Soda 2 lt',
    'prod.beb10.desc': 'Soda 2 lt',
    'prod.beb11.name': 'Yukery 250 ml',
    'prod.beb11.desc': 'Yukery 250 ml',
    'rev.0.name': 'John Doe',
    'rev.0.body': 'The best Chinese food I have ever tried. The flavor is authentic and the portions are generous.',
    'rev.1.name': 'Maria Garcia',
    'rev.1.body': 'The service is incredibly fast. I ordered for home delivery and it arrived hot and fresh in 20 minutes.',
    'rev.2.name': 'Charles Smith',
    'rev.2.body': 'Excellent quality-price. The locations are very clean and the atmosphere is great for eating with friends.',
    'rev.3.name': 'Ann Lopez',
    'rev.3.body': 'I love the Orange chicken, it has the perfect texture. Definitely my favorite place for Sundays.',
  },
  zh: {
    'nav.about': '关于我们',
    'nav.featured': '特色菜肴',
    'nav.locations': '分店',
    'nav.reviews': '评价',
    'nav.socials': '社交媒体',
    'nav.orderNow': '立即下单',
    'nav.home': '首页',
    'nav.menu': '菜单',
    'hero.tagline': '美味佳肴，直达餐桌！',
    'hero.cta': '开始下单',
    'about.title': '关于我们',
    'about.default': '在熊猫快餐，我们致力于提供最佳的餐饮体验。每一份订单都保证新鲜、高质量和我们独特的风味。',
    'featured.badge': '熊猫推荐',
    'featured.title': '精选菜品',
    'featured.viewAll': '查看全部菜单',
    'locations.badge': '找到我们',
    'locations.title': '我们的分店',
    'locations.open': '正在营业',
    'locations.closed': '休息中',
    'locations.closedToday': '今日休息',
    'reviews.badge': '熊猫社区',
    'reviews.title': '客户评价',
    'socials.title': '加入我们的大家庭！',
    'socials.tagline': '关注我们的社交网络，不错过任何促销活动和专属抽奖。',
    'cta.title': '饿了吗？',
    'cta.button': '查看完整菜单',
    'menu.welcome': '用餐愉快！',
    'menu.empty': '此处没有产品',
    'menu.ready': '准备下单',
    'menu.viewCart': '查看购物车',
    'menu.total': '总计',
    'menu.price': '价格',
    'menu.outOfStock': '已售罄',
    'cart.title': '您的订单',
    'cart.checkout': '结算',
    'cart.empty': '购物车是空的',
    'cart.emptyTagline': '添加一些美味的东西开始吧！',
    'cart.specialInstructions': '有什么特殊要求吗？',
    'cart.delivery': 'Delivery',
    'cart.fullName': '姓名',
    'cart.whatsapp': '联系电话',
    'cart.address': '详细送货地址',
    'cart.mapSelect': '在地图上选择',
    'cart.reference': '参考地点（房子颜色、附近商店...）',
    'cart.mapTitle': '送货位置',
    'cart.mapTagline': '将地图拖动到您的门前',
    'cart.closeMap': '关闭地图',
    'cart.shipping': '配送费',
    'cart.orderTotal': '订单总计',
    'cart.inBolivares': '玻利瓦尔金额',
    'cart.continue': '继续结算',
    'cart.back': '返回',
    'cart.confirmWhatsApp': '通过WhatsApp下单',
    'cart.mapHint': '点击地图设置您的位置',
    'cart.useLocation': '使用我的当前位置',
    'cart.locating': '正在定位...',
    'welcome.greeting': '欢迎光临！',
    'welcome.selectLocation': '选择您喜欢的分店',
    'welcome.noLocations': '目前没有可用的分店',
    'welcome.admin': '系统配置',
    'cat.combos': '套餐',
    'cat.especiales': '特色',
    'cat.raciones': '份量',
    'cat.entradas': '开胃菜',
    'cat.bebidas': '饮料',
    'loc.prebo.name': 'Prebo',
    'loc.prebo.address': '瓦伦西亚，安德烈斯·埃洛伊·布兰科大道',
    'loc.naguanagua.name': 'Naguanagua',
    'loc.naguanagua.address': 'Naguanagua，La Granja 购物中心',
    'loc.san-diego.name': 'San Diego',
    'loc.san-diego.address': '圣地亚哥，唐·朱利奥·森特诺大道',
    'prod.combo1.name': '套餐 #1',
    'prod.combo1.desc': '熊猫炸鸡(3块) + 薯条或特色杂碎',
    'prod.combo2.name': '套餐 #2',
    'prod.combo2.desc': '熊猫炸鸡(6块) + 薯条或特色杂碎',
    'prod.combo3.name': '套餐 #3',
    'prod.combo3.desc': '熊猫炸鸡(12块) + 薯条或特色杂碎',
    'prod.combo4.name': '套餐 #4',
    'prod.combo4.desc': '熊猫炸鸡(6块) + 特色杂碎 + 2春卷 + 4咕噜鸡 + 薯条',
    'prod.combo5.name': '套餐 #5',
    'prod.combo5.desc': '特色炒饭(虾,鸡肉,火腿) + 6咕噜鸡 + 薯条',
    'prod.combo6.name': '套餐 #6',
    'prod.combo6.desc': '特色炒饭(虾,鸡肉,火腿) + 特色杂碎 + 6椒盐排骨',
    'prod.combo7.name': '套餐 #7',
    'prod.combo7.desc': '特色炒饭(虾,鸡肉,火腿) + 特色杂碎 + 1春卷',
    'prod.combo8.name': '套餐 #8',
    'prod.combo8.desc': '特色炒饭(虾,鸡肉,火腿) + 特色杂碎 + 1烤排骨',
    'prod.combo9.name': '套餐 #9',
    'prod.combo9.desc': '特色炒饭(虾,鸡肉,火腿) + 薯条 + 1烤排骨',
    'prod.combo10.name': '套餐 #10',
    'prod.combo10.desc': '特色炒饭(虾,鸡肉,火腿) + 1春卷 + 6椒盐排骨',
    'prod.combo11.name': '套餐 #11',
    'prod.combo11.desc': '特色炒饭(虾,鸡肉,火腿) + 薯条 + 6椒盐排骨',
    'prod.combo12.name': '套餐 #12',
    'prod.combo12.desc': '特色炒饭(虾,鸡肉,火腿) + 咕噜鸡(3块) + 3椒盐排骨',
    'prod.combo13.name': '套餐 #13',
    'prod.combo13.desc': '特色炒饭(虾,鸡肉,火腿) + 咕噜鸡(6块) + 特色杂碎',
    'prod.combo14.name': '套餐 #14',
    'prod.combo14.desc': '特色炒饭(虾,鸡肉,火腿) + 咕噜鸡(6块) + 1春卷',
    'prod.combo15.name': '套餐 #15',
    'prod.combo15.desc': '特色炒饭(虾,鸡肉,火腿) + 1烤排骨 + 1春卷',
    'prod.combo16.name': '套餐 #16',
    'prod.combo16.desc': '特色炒饭(虾,鸡肉,火腿) + 薯条 + 特色杂碎',
    'prod.combo17.name': '套餐 #17',
    'prod.combo17.desc': '特色炒饭(虾,鸡肉,火腿) + 咕噜鸡(3块) + 1烤排骨',
    'prod.combo18.name': '套餐 #18',
    'prod.combo18.desc': '特色炒饭(虾,鸡肉,火腿) + 薯条 + 1春卷',
    'prod.combo19.name': '套餐 #19',
    'prod.combo19.desc': '半份特色炒饭(虾,鸡肉,火腿) + 特色杂碎',
    'prod.combo20.name': '套餐 #20',
    'prod.combo20.desc': '半份特色炒饭(虾,鸡肉,火腿) + 3份咕噜鸡',
    'prod.combo21.name': '套餐 #21',
    'prod.combo21.desc': '半份特色炒饭(虾,鸡肉,火腿) + 1炸鸡',
    'prod.combo22.name': '套餐 #22',
    'prod.combo22.desc': '特色炒饭(虾,鸡肉,火腿) + 2炸鸡 + 薯条或特色杂碎',
    'prod.combo23.name': '套餐 #23',
    'prod.combo23.desc': '炒饭 + 菠萝鸡 + 薯条或杂碎',
    'prod.combo24.name': '套餐 #24',
    'prod.combo24.desc': '炒饭 + 芝麻鸡 + 薯条或杂碎',
    'prod.esp1.name': '特色炒饭',
    'prod.esp1.desc': '特色炒饭(虾,鸡肉,火腿)',
    'prod.esp2.name': '半份特色炒饭',
    'prod.esp2.desc': '半份特色炒饭(虾,鸡肉,火腿)',
    'prod.esp3.name': '特色杂碎',
    'prod.esp3.desc': '特色杂碎(虾,鸡肉,火腿)',
    'prod.esp4.name': '半份特色杂碎',
    'prod.esp4.desc': '半份特色杂碎(虾,鸡肉,火腿)',
    'prod.rac1.name': '蔬菜鸡肉',
    'prod.rac1.desc': '蔬菜鸡肉(120克)',
    'prod.rac2.name': '咕噜鸡',
    'prod.rac2.desc': '咕噜鸡(15块)',
    'prod.rac3.name': '蜂蜜芝麻鸡',
    'prod.rac3.desc': '蜂蜜芝麻鸡(15块)',
    'prod.rac4.name': '椒盐排骨',
    'prod.rac4.desc': '椒盐排骨(320克)',
    'prod.rac5.name': '烤排骨',
    'prod.rac5.desc': '烤排骨(4块)',
    'prod.rac6.name': '椒盐虾',
    'prod.rac6.desc': '椒盐虾(30/40只)',
    'prod.rac7.name': '炒面',
    'prod.rac7.desc': '炒面(虾,鸡肉,火腿)',
    'prod.rac8.name': '半份炒面',
    'prod.rac8.desc': '半份炒面(虾,鸡肉,火腿)',
    'prod.ent1.name': '薯条',
    'prod.ent1.desc': '薯条(280克)',
    'prod.ent2.name': '春卷',
    'prod.ent2.desc': '春卷(2块)',
    'prod.beb1.name': 'Minalba水 355ml',
    'prod.beb1.desc': 'Minalba水 355ml',
    'prod.beb2.name': 'Minalba水 600ml',
    'prod.beb2.desc': 'Minalba水 600ml',
    'prod.beb3.name': 'Malta瓶装 250ml',
    'prod.beb3.desc': 'Malta瓶装 250ml',
    'prod.beb4.name': 'Malta罐装 355ml',
    'prod.beb4.desc': 'Malta罐装 355ml',
    'prod.beb5.name': 'Gatorade 500ml',
    'prod.beb5.desc': 'Gatorade 500ml',
    'prod.beb6.name': 'Lipton 500ml',
    'prod.beb6.desc': 'Lipton 500ml',
    'prod.beb7.name': '汽水罐装 355ml',
    'prod.beb7.desc': '汽水罐装 355ml',
    'prod.beb8.name': '汽水 1升',
    'prod.beb8.desc': '汽水 1升',
    'prod.beb9.name': '汽水 1.5升',
    'prod.beb9.desc': '汽水 1.5升',
    'prod.beb10.name': '汽水 2升',
    'prod.beb10.desc': '汽水 2升',
    'prod.beb11.name': 'Yukery 250ml',
    'prod.beb11.desc': 'Yukery 250ml',
    'rev.0.name': '张三',
    'rev.0.body': '我尝试过的最好的中餐。味道地道，分量足。',
    'rev.1.name': '李四',
    'rev.1.body': '服务非常快。我订了外卖，20分钟就送到，又热又新鲜。',
    'rev.2.name': '王五',
    'rev.2.body': '物美价廉。分店非常干净，环境非常适合和朋友一起吃饭。',
    'rev.3.name': '赵六',
    'rev.3.body': '我爱陈皮鸡，它的质地完美。绝对是我周日最喜欢去的地方。',
  }
};
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);
export function LanguageProvider({ children }: { children: ReactNode }) { const [language, setLanguage] = useState<Language>('es');
const t = (key: string) => { return translations[language][key] || key; }; return ( <LanguageContext.Provider value={{ language, setLanguage, t }}> {children} </LanguageContext.Provider> );}

export function useLanguage() { const context = useContext(LanguageContext);
if (context === undefined) { throw new Error('useLanguage must be used within a LanguageProvider'); }
return context;}
